'use strict';
const levels = [
{title:'LE CADRE',tag:'ZONE LARGE',hook:'Comprendre la situation globale.',explanation:'Avant de chercher un point précis, comprenez le contexte. Cette première étape réduit le champ de recherche et prépare l’utilisation des outils.',questions:['Êtes-vous en vacances, en déplacement professionnel ou sur un trajet habituel ?','Dans quel pays êtes-vous ? Dans quelle région ?','Êtes-vous seul ?'],tool:'Google Maps',links:[['Google Maps','https://www.google.com/maps/']],toolText:'Situer progressivement le pays et la région à partir des informations du client.'},
{title:'LE TRAJET',tag:'AXE DE DÉPLACEMENT',hook:'Reconstruire l’axe de déplacement.',explanation:'Le trajet du client doit progressivement conduire jusqu’à sa position. D’une zone géographique large, on passe à un axe.',questions:['D’où êtes-vous parti et quelle est votre destination ?','Dans quel sens circulez-vous ? Vers quelle ville ?','Quel est le nom ou le numéro de la route empruntée ?','Sur quel type de voie circulez-vous ?','Quel environnement voyez-vous ?','Quelles villes avez-vous traversées ?','Quels repères avez-vous dépassés ? Depuis combien de temps ?'],tool:'Google Maps',links:[['Google Maps','https://www.google.com/maps/']],toolText:'Reconstituer l’itinéraire après avoir recueilli les informations. La carte ne doit pas devancer la compréhension partagée.'},
{title:'LES REPÈRES',tag:'POINT PRÉCIS',hook:'Fixer un point précis.',explanation:'Un repère est utile s’il réduit réellement la zone de recherche : point kilométrique, panneau, enseigne, magasin, restaurant, monument, pont ou cours d’eau.',questions:['Qu’est-ce qui, autour de vous, peut permettre de déterminer précisément votre position ?','Voyez-vous un point kilométrique, un panneau ou une enseigne identifiable ?','Y a-t-il une intersection, un monument ou un bâtiment reconnaissable ?','Voyez-vous une station-service ou un commerce ? Quel est son nom ?'],tool:'Point kilométrique · Vue satellite ou 3D',links:[['Google Maps','https://www.google.com/maps/'],['Google Earth','https://earth.google.com/web/'],['Busca PK','https://buscapk.es/']],toolText:'Transformer une information kilométrique en position cartographique, puis croiser les sources. Google Earth ou la vue satellite aide à vérifier les éléments physiques.'},
{title:'LA CONFIRMATION',tag:'CERTITUDE',hook:'Valider l’hypothèse.',explanation:'Une position probable n’est pas encore une position certaine. Validez votre hypothèse avec le client, puis assurez-vous qu’elle est exploitable par le prestataire.',questions:['Le lieu repéré sur la carte correspond-il à ce que vous voyez devant vous ?','Les repères à votre droite et à votre gauche correspondent-ils ?','La route et le sens de circulation sont-ils cohérents avec votre trajet ?','Quel accès permettra au prestataire de vous rejoindre précisément ?'],tool:'Vue satellite / 3D',links:[['Google Earth','https://earth.google.com/web/'],['Google Maps','https://www.google.com/maps/']],toolText:'Recouper les éléments physiques observés par le client. Transmettre un lieu identifiable et les indications d’accès utiles, dont le sens de circulation.'}
];
const frame=document.getElementById('video-frame');window.addEventListener('message',event=>{if(event.source!==frame.contentWindow||event.origin!==location.origin||event.data?.type!=='localisation-player-height')return;const height=Number(event.data.height);if(Number.isFinite(height)&&height>100&&height<2400){frame.style.height=Math.ceil(height)+'px';frame.style.aspectRatio='auto'}});

const root=document.querySelector('.method-3d'), stage=root.querySelector('.cone-stage'), mount=root.querySelector('.cone-canvas'), host=root.querySelector('.panel-host'), controls=root.querySelector('.cone-controls');
const motion=matchMedia('(prefers-reduced-motion: reduce)');
let active=0, emphasized=-1, changeTimer;
const buttons=levels.map((level,i)=>{const b=document.createElement('button');b.type='button';b.className='cone-step';b.innerHTML=`<span>0${i+1}</span>${level.title}`;b.setAttribute('aria-pressed',String(i===0));b.setAttribute('aria-controls','cone-detail');b.addEventListener('click',()=>select(i));b.addEventListener('focus',()=>select(i));b.addEventListener('keydown',e=>{let j;if(e.key==='ArrowDown'||e.key==='ArrowRight')j=(i+1)%4;if(e.key==='ArrowUp'||e.key==='ArrowLeft')j=(i+3)%4;if(e.key==='Home')j=0;if(e.key==='End')j=3;if(j!==undefined){e.preventDefault();buttons[j].focus()}if(e.key==='Escape')emphasized=-1});controls.append(b);return b});
function renderPanel(){const l=levels[active];host.innerHTML=`<section class="detail-panel" id="cone-detail" aria-labelledby="cone-title"><p class="eyebrow">0${active+1} — ${l.title} / ${l.tag}</p><h3 id="cone-title">${l.hook}</h3><p class="explanation">${l.explanation}</p><ul class="questions">${l.questions.map(q=>`<li>${q}</li>`).join('')}</ul><p class="tools"><strong>${l.tool}</strong>${l.toolText}</p><div class="tool-links" aria-label="Outils de localisation">${l.links.map(([name,url])=>`<a href="${url}" target="_blank" rel="noopener noreferrer" aria-label="${name} (nouvel onglet)">${name} ↗</a>`).join('')}</div><button class="text-button">${active<3?'Explorer le niveau suivant →':'Revenir au cadre ↺'}</button></section>`;host.querySelector('button').addEventListener('click',()=>select((active+1)%4));host.classList.remove('changing')}
function select(i){emphasized=i;if(i===active)return;active=i;buttons.forEach((b,j)=>b.setAttribute('aria-pressed',String(i===j)));clearTimeout(changeTimer);host.classList.add('changing');changeTimer=setTimeout(renderPanel,motion.matches?0:140)}
renderPanel();
function fallback(){root.classList.add('no-webgl');mount.replaceChildren();stage.setAttribute('aria-label','Méthode du général au particulier : sélectionner une étape ci-dessous');root.querySelector('.cone-hint').textContent='Sélectionnez une étape pour explorer les questions.';}
async function init(){try{
const THREE=await import('./vendor/three.module.min.js');
const renderer=new THREE.WebGLRenderer({alpha:true,antialias:true,powerPreference:'low-power'});renderer.setPixelRatio(Math.min(devicePixelRatio,1.6));renderer.setClearColor(0x000000,0);renderer.outputColorSpace=THREE.SRGBColorSpace;mount.append(renderer.domElement);
const scene=new THREE.Scene(),camera=new THREE.PerspectiveCamera(34,1,.1,30);camera.position.set(0,2.25,8.3);camera.lookAt(0,0,0);
scene.add(new THREE.HemisphereLight(0xf6fbff,0x586b78,2.5));const key=new THREE.DirectionalLight(0xffffff,3.1);key.position.set(-3,5,5);scene.add(key);const fill=new THREE.DirectionalLight(0xb6d1e0,1);fill.position.set(4,1,-2);scene.add(fill);
const group=new THREE.Group();scene.add(group);group.rotation.y=-.12;
const colors=[0x7dcfc8,0x8daee6,0xb9a0df,0xeea077],radii=[1.6,1.21,.82,.43,0], meshes=[];
for(let i=0;i<4;i++){const geometry=new THREE.CylinderGeometry(radii[i],radii[i+1],.73,64,1,false);const material=new THREE.MeshStandardMaterial({color:colors[i],roughness:.78,metalness:0});const mesh=new THREE.Mesh(geometry,material);mesh.position.y=1.23-i*.82;mesh.userData.level=i;mesh.userData.baseY=mesh.position.y;group.add(mesh);meshes.push(mesh)}
const raycaster=new THREE.Raycaster(),pointer=new THREE.Vector2(3,3);let targetX=0,targetY=0,inside=false,visible=true,raf=0,last=0;
function hit(e){const rect=renderer.domElement.getBoundingClientRect();pointer.set((e.clientX-rect.left)/rect.width*2-1,-(e.clientY-rect.top)/rect.height*2+1);camera.updateMatrixWorld();group.updateMatrixWorld(true);raycaster.setFromCamera(pointer,camera);return raycaster.intersectObjects(meshes,false)[0]?.object.userData.level}
mount.addEventListener('pointermove',e=>{if(e.pointerType==='touch')return;inside=true;const i=hit(e);targetX=motion.matches?0:-pointer.y*.055;targetY=motion.matches?0:pointer.x*.085;mount.style.cursor=i===undefined?'default':'pointer';if(i!==undefined)select(i);else emphasized=-1});
mount.addEventListener('pointerleave',()=>{inside=false;targetX=targetY=0;emphasized=-1;mount.style.cursor='default'});
let down;mount.addEventListener('pointerdown',e=>{down={x:e.clientX,y:e.clientY}});mount.addEventListener('pointerup',e=>{if(!down||Math.hypot(e.clientX-down.x,e.clientY-down.y)>12)return;const i=hit(e);if(i!==undefined)select(i);down=null});mount.addEventListener('pointercancel',()=>{down=null});
const tint=new THREE.Color(),base=new THREE.Color();
function draw(time){raf=0;if(!visible||document.hidden)return;const dt=Math.min((time-last)/1000||.016,.05);last=time;const k=motion.matches?1:1-Math.exp(-7*dt);group.rotation.x+=(targetX-group.rotation.x)*k;group.rotation.y+=(-.12+targetY-group.rotation.y)*k;group.position.y+=((motion.matches||inside?0:Math.sin(time*.00055)*.014)-group.position.y)*k;
meshes.forEach((m,i)=>{const chosen=emphasized===i;const z=chosen?.27:0;const x=chosen?.065:0;m.position.z+=(z-m.position.z)*k;m.position.x+=(x-m.position.x)*k;base.setHex(colors[i]);tint.copy(base).multiplyScalar(chosen?1.08:emphasized>=0?.9:1);m.material.color.lerp(tint,k)});renderer.render(scene,camera);raf=requestAnimationFrame(draw)}
function resume(){if(!raf&&visible&&!document.hidden){last=performance.now();raf=requestAnimationFrame(draw)}}
const resize=new ResizeObserver(()=>{const w=mount.clientWidth,h=mount.clientHeight;renderer.setSize(w,h);camera.aspect=w/h;camera.position.z=camera.aspect<.9?9.5:8.3;camera.updateProjectionMatrix();resume()});resize.observe(mount);
const observer=new IntersectionObserver(entries=>{visible=entries[0].isIntersecting;if(visible)resume();else{cancelAnimationFrame(raf);raf=0}},{rootMargin:'100px'});observer.observe(stage);document.addEventListener('visibilitychange',resume);
renderer.domElement.addEventListener('webglcontextlost',e=>{e.preventDefault();cancelAnimationFrame(raf);visible=false;observer.disconnect();resize.disconnect();fallback()});resume();
}catch(error){fallback();console.warn('La vue 3D est indisponible.',error)}}
const lazy=new IntersectionObserver(entries=>{if(entries.some(e=>e.isIntersecting)){lazy.disconnect();init()}},{rootMargin:'500px'});lazy.observe(stage);
